import { z } from "zod";

export const identifierSchema = z.string().trim().min(1).max(100);
export const localeSchema = z.enum(["ar", "en"]);
export const directionSchema = z.enum(["rtl", "ltr"]);
export const themeSchema = z.enum(["light", "dark"]);
export const environmentSchema = z.enum(["production", "staging", "development"]);
export const platformFilterSchema = z.enum(["all", "ios", "android"]);
export const isoDateSchema = z.iso.datetime({ offset: true });
export const searchTextSchema = z.string().trim().max(100);
export const paginationSchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),
});
export const routeSchema = z.enum([
  "/admin",
  "/admin/users",
  "/admin/imports",
  "/admin/imports/sessions",
  "/admin/imports/failed",
  "/admin/imports/low-confidence",
  "/admin/imports/duplicates",
  "/admin/imports/unsupported",
  "/admin/parsers/banks",
  "/admin/parsers/senders",
  "/admin/parsers/rules",
  "/admin/parsers/test-cases",
  "/admin/parsers/versions",
  "/admin/parsers/merchant-rules",
  "/admin/parsers/category-rules",
  "/admin/system-health",
  "/admin/system-health/api",
  "/admin/system-health/database",
  "/admin/system-health/storage",
  "/admin/system-health/providers",
  "/admin/jobs/queues",
  "/admin/jobs/runs",
  "/admin/jobs/runs/JOB-DEMO-FAILED-01",
  "/admin/jobs/scheduled",
  "/admin/admin-team",
  "/admin/admin-team/invite",
  "/admin/admin-team/ADM-DEMO-SECURITY-02",
  "/admin/roles",
  "/admin/roles/new",
  "/admin/roles/permissions",
  "/admin/roles/ROLE-DEMO-SUPPORT",
  "/admin/roles/ROLE-DEMO-CUSTOM-01/edit",
  "/admin/settings",
  "/admin/settings/mobile",
  "/admin/settings/feature-flags",
  "/admin/settings/imports",
  "/admin/settings/ai",
  "/admin/settings/subscriptions",
  "/admin/settings/security",
  "/admin/settings/maintenance",
  "/admin/access-requests",
  "/admin/subscriptions",
  "/admin/payments",
  "/admin/ai",
  "/admin/ai/providers",
  "/admin/ai/usage",
  "/admin/support",
  "/admin/support/tickets",
  "/admin/support/tickets/TKT-1001",
  "/admin/support/categories",
  "/admin/content/categories",
  "/admin/content/categories/CAT-1001",
  "/admin/feedback",
  "/admin/feedback/FDB-1001",
  "/admin/feedback/abuse",
  "/admin/content/tips",
  "/admin/content/faqs",
  "/admin/content/onboarding",
  "/admin/content/help-center",
  "/admin/content/announcements",
  "/admin/content/email-templates",
  "/admin/content/push-templates",
  "/admin/notifications",
  "/admin/notifications/campaigns",
  "/admin/notifications/campaigns/new",
  "/admin/notifications/campaigns/CMP-1001",
  "/admin/notifications/transactional",
  "/admin/notifications/delivery-logs",
  "/admin/security",
  "/admin/security/authentication-events",
  "/admin/security/suspicious-activity",
  "/admin/security/admins",
  "/admin/security/permission-changes",
  "/admin/security/support-access",
  "/admin/security/incidents/INC-1001",
  "/admin/audit",
  "/admin/audit/AUD-1001",
  "/admin/data-requests/exports",
  "/admin/data-requests/exports/EXP-1001",
  "/admin/data-requests/deletions",
  "/admin/data-requests/deletions/DEL-1001",
  "/admin/data-requests/retention",
]);
