import { z } from 'zod';

export const safeFailureSchema = z.enum(['validation', 'permission', 'unavailable', 'offline', 'conflict', 'expired', 'limit_reached', 'cancelled', 'representative_failure', 'review_required']);
export type SafeFailureCategory = z.infer<typeof safeFailureSchema>;
export const notificationCategorySchema = z.enum(['transaction', 'income', 'obligation', 'budget', 'salary', 'savings', 'report', 'assistant', 'security', 'system']);
export type NotificationCategory = z.infer<typeof notificationCategorySchema>;
export const notificationTargetSchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('transaction'), transactionId: z.string().min(1) }), z.object({ kind: z.literal('review'), reviewId: z.string().min(1) }), z.object({ kind: z.literal('obligation'), obligationId: z.string().min(1) }), z.object({ kind: z.literal('budget'), budgetId: z.string().min(1) }), z.object({ kind: z.literal('salary'), cycleKey: z.string().min(1) }), z.object({ kind: z.literal('goal'), goalId: z.string().min(1) }), z.object({ kind: z.literal('report'), periodKind: z.string().min(1), anchorDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/) }), z.object({ kind: z.literal('assistant'), conversationId: z.string().min(1), responseId: z.string().min(1) }), z.object({ kind: z.literal('security'), securityEventId: z.string().min(1) }), z.object({ kind: z.literal('settings'), key: z.enum(['security', 'notifications', 'privacy']) })
]);
export type NotificationTarget = z.infer<typeof notificationTargetSchema>;
export const notificationActionSchema = z.object({ kind: z.enum(['view', 'edit', 'undo']), expiresAt: z.number().int().nonnegative().nullable(), sourceVersion: z.number().int().nonnegative().nullable() }).superRefine((value, ctx) => { if (value.kind === 'undo' && (value.expiresAt === null || value.sourceVersion === null)) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'undo requires expiry and source version' }); });
export type NotificationActionKind = z.infer<typeof notificationActionSchema>['kind'];
export const notificationEventSchema = z.object({ id: z.string().min(1), eventKey: z.string().min(1), category: notificationCategorySchema, eventType: z.string().min(1), titleKey: z.string().min(1), bodyKey: z.string().min(1), messageValues: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])), sensitivity: z.enum(['public', 'protected', 'security_sensitive']), target: notificationTargetSchema.nullable(), availableActions: z.array(notificationActionSchema), occurredAt: z.number().int().nonnegative(), readAt: z.number().int().nonnegative().nullable(), deletedAt: z.number().int().nonnegative().nullable(), phoneStatus: z.enum(['not_requested', 'deferred', 'summarized', 'presented_local', 'suppressed_preference', 'suppressed_private', 'permission_denied', 'failed_mock']), syncStatus: z.enum(['synced', 'pending', 'failed']), safeFailure: safeFailureSchema.nullable() });
export type NotificationEvent = z.infer<typeof notificationEventSchema>;
const timeOfDaySchema = z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/);
const timeZoneSchema = z.string().refine((value) => {
  try { new Intl.DateTimeFormat('en', { timeZone: value }).format(); return true; } catch { return false; }
}, 'invalid timezone');
export const notificationPreferencesSchema = z.object({ version: z.number().int().positive(), phoneEnabled: z.boolean(), categoryEnabled: z.record(notificationCategorySchema, z.boolean()), quietHours: z.object({ enabled: z.boolean(), start: timeOfDaySchema, end: timeOfDaySchema, weekdays: z.array(z.number().int().min(0).max(6)), timeZone: timeZoneSchema }), dailySummary: z.object({ enabled: z.boolean(), time: timeOfDaySchema }), weeklySummary: z.object({ enabled: z.boolean(), weekday: z.number().int().min(0).max(6), time: timeOfDaySchema }), hideAmountsOnLockScreen: z.boolean(), permissionState: z.enum(['not_requested', 'granted', 'denied', 'permanently_denied', 'unavailable']), updatedAt: z.number().int().nonnegative() });
export type NotificationPreferences = z.infer<typeof notificationPreferencesSchema>;
export type NotificationPreferencesInput = Omit<NotificationPreferences, 'version' | 'updatedAt'>;
export interface Page<T> { items: T[]; nextCursor: string | null; total: number; }
export type NotificationListQuery = { category?: NotificationCategory; unreadOnly?: boolean; cursor?: string; pageSize?: number };
export type NotificationPermissionState = NotificationPreferences['permissionState'];
export const notificationActionResolutionSchema = z.object({ status: z.enum(['available', 'expired', 'unavailable', 'unlock_required']), target: notificationTargetSchema.nullable(), action: z.enum(['view', 'edit', 'undo']) });
export const notificationTargetResolutionSchema = z.object({ status: z.enum(['exact', 'fallback', 'unavailable', 'unlock_required']), target: notificationTargetSchema.nullable() }).superRefine((value, ctx) => { if (value.status === 'exact' && !value.target) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'exact needs target' }); });
export type NotificationTargetResolution = z.infer<typeof notificationTargetResolutionSchema>;
export const notificationPolicyInputSchema = z.object({ category: notificationCategorySchema, eventType: z.string().min(1), sensitivity: z.enum(['public', 'protected', 'security_sensitive']), preferences: notificationPreferencesSchema, permission: z.enum(['not_requested', 'granted', 'denied', 'permanently_denied', 'unavailable']), profileTimeZone: z.string().min(1), now: z.number().int().nonnegative(), hideBalances: z.boolean(), summaryWindow: z.enum(['none', 'daily', 'weekly']) });
export const notificationPolicyResultSchema = z.object({ outcome: z.enum(['present_local', 'defer_quiet_hours', 'include_daily_summary', 'include_weekly_summary', 'suppress_category', 'suppress_phone_disabled', 'suppress_permission', 'suppress_private']) });
export function isDuplicateEventKey(events: readonly Pick<NotificationEvent, 'eventKey'>[], eventKey: string) { return events.some((event) => event.eventKey === eventKey); }
export function tombstoneNotification<T>(event: NotificationEvent, source: T, deletedAt: number) { return { notification: { ...event, deletedAt, syncStatus: 'pending' as const }, source }; }
export function createNotificationPreferences(updatedAt: number): NotificationPreferences { return { version: 1, phoneEnabled: false, categoryEnabled: Object.fromEntries(notificationCategorySchema.options.map((category) => [category, true])) as Record<NotificationCategory, boolean>, quietHours: { enabled: false, start: '22:00', end: '07:00', weekdays: [0, 1, 2, 3, 4, 5, 6], timeZone: 'Asia/Riyadh' }, dailySummary: { enabled: false, time: '09:00' }, weeklySummary: { enabled: false, weekday: 0, time: '09:00' }, hideAmountsOnLockScreen: true, permissionState: 'not_requested', updatedAt }; }
