import { z } from 'zod';
import { safeFailureSchema } from './notifications';

export const subscriptionOfferSchema = z.object({ offerId: z.string().min(1), plan: z.enum(['free', 'basic', 'premium']), billingPeriod: z.enum(['none', 'monthly', 'annual']), priceMinor: z.number().int().nonnegative(), currency: z.string().regex(/^[A-Z]{3}$/), features: z.array(z.string()), limits: z.record(z.string(), z.number().int().nonnegative()), trial: z.object({ eligible: z.boolean(), durationDays: z.number().int().nonnegative(), trialPriceMinor: z.number().int().nonnegative(), postTrialPriceMinor: z.number().int().nonnegative() }).strict(), renewalTermsKey: z.string().min(1), cancellationTermsKey: z.string().min(1), catalogVersion: z.string().min(1), effectiveAt: z.number().int().nonnegative() }).strict();
export type SubscriptionOffer = z.infer<typeof subscriptionOfferSchema>;
export const subscriptionOfferCatalogSchema = z.object({ version: z.string().min(1), offers: z.array(subscriptionOfferSchema).min(1) }).superRefine((catalog, ctx) => { if (catalog.offers.some((offer) => offer.catalogVersion !== catalog.version)) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'one catalog version' }); });
export type SubscriptionOfferCatalog = z.infer<typeof subscriptionOfferCatalogSchema>;
export const subscriptionStateSchema = z.object({ plan: z.enum(['free', 'basic', 'premium']), status: z.enum(['free', 'trialing', 'active', 'cancellation_scheduled', 'expired', 'representative_payment_failed']), offerId: z.string().min(1), catalogVersion: z.string().min(1), startedAt: z.number().int().nonnegative().nullable(), trialEndsAt: z.number().int().nonnegative().nullable(), renewsAt: z.number().int().nonnegative().nullable(), accessEndsAt: z.number().int().nonnegative().nullable(), limits: z.record(z.string(), z.number().int().nonnegative()), version: z.number().int().positive(), paidContentAccess: z.enum(['editable', 'read_only']), updatedAt: z.number().int().nonnegative() }).superRefine((value, ctx) => { if (value.status === 'trialing' && value.trialEndsAt === null) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'trial needs end' }); if (['active', 'cancellation_scheduled'].includes(value.status) && value.renewsAt === null) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'active subscription needs renewal' }); if (['expired', 'representative_payment_failed'].includes(value.status) && value.paidContentAccess !== 'read_only') ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'lost entitlement stays readable' }); });
export type SubscriptionState = z.infer<typeof subscriptionStateSchema>;
export const subscriptionOperationSchema = z.object({ id: z.string().min(1), operationId: z.string().min(1), kind: z.enum(['start_trial', 'purchase', 'restore', 'change_plan', 'cancel', 'renew_mock']), offerId: z.string().min(1), catalogVersion: z.string().min(1), priorStateVersion: z.number().int().positive(), status: z.enum(['review', 'pending', 'succeeded', 'failed', 'cancelled']), requestedAt: z.number().int().nonnegative(), completedAt: z.number().int().nonnegative().nullable(), safeFailure: safeFailureSchema.nullable(), resultStateVersion: z.number().int().positive().nullable() }).superRefine((value, ctx) => { if (value.status === 'succeeded' && (value.completedAt === null || value.resultStateVersion === null)) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'success has result' }); });
export type SubscriptionOperation = z.infer<typeof subscriptionOperationSchema>;
export type SubscriptionOperationInput = Pick<SubscriptionOperation, 'kind' | 'offerId' | 'catalogVersion'>;
export function canChangeEntitlement(status: SubscriptionOperation['status']) { return status === 'succeeded'; }
export function hasSingleCatalogVersion(offers: readonly SubscriptionOffer[]) { return new Set(offers.map((offer) => offer.catalogVersion)).size <= 1; }
export function preservesPaidContent(state: SubscriptionState) { return !['expired', 'representative_payment_failed'].includes(state.status) || state.paidContentAccess === 'read_only'; }
export function canTransitionSubscription(from: SubscriptionState['status'], to: SubscriptionState['status']) { return (from === 'free' && ['trialing', 'active'].includes(to)) || (from === 'trialing' && ['active', 'expired'].includes(to)) || (from === 'active' && ['cancellation_scheduled', 'expired', 'representative_payment_failed'].includes(to)) || (from === 'cancellation_scheduled' && ['active', 'expired'].includes(to)) || (from === 'expired' && to === 'active'); }
export function replaySubscriptionOperation(operations: readonly SubscriptionOperation[], operationId: string) { return operations.find((operation) => operation.operationId === operationId) ?? null; }
