import { z } from 'zod';
import { safeFailureSchema } from './notifications';

export const supportContextSchema = z.object({ itemId: z.string().min(1), itemKind: z.enum(['transaction', 'assistant_response']), category: z.string().min(1).max(64), status: z.string().min(1).max(64), appVersion: z.string().min(1).max(32), diagnosticCategory: z.string().min(1).max(64) }).strict();
export type SupportContext = z.infer<typeof supportContextSchema>;
const draftFields = { id: z.string().min(1), category: z.string().min(1).max(64), subject: z.string().min(1).max(160), description: z.string().min(1).max(4000), status: z.enum(['draft', 'validating', 'failed']), updatedAt: z.number().int().nonnegative() };
const transactionContext = supportContextSchema.extend({ itemKind: z.literal('transaction') }); const assistantContext = supportContextSchema.extend({ itemKind: z.literal('assistant_response') });
export const supportDraftSchema = z.discriminatedUnion('mode', [z.object({ ...draftFields, mode: z.literal('ticket'), ticketId: z.null(), context: z.null() }).strict(), z.object({ ...draftFields, mode: z.literal('reply'), ticketId: z.string().min(1), context: z.null() }).strict(), z.object({ ...draftFields, mode: z.literal('feedback'), ticketId: z.null(), context: z.null() }).strict(), z.object({ ...draftFields, mode: z.literal('transaction_report'), ticketId: z.null(), context: transactionContext }).strict(), z.object({ ...draftFields, mode: z.literal('assistant_report'), ticketId: z.null(), context: assistantContext }).strict()]);
export type SupportDraft = z.infer<typeof supportDraftSchema>; export type SupportDraftInput = Omit<SupportDraft, 'status' | 'updatedAt'>;
export const supportMessageSchema = z.object({ id: z.string().min(1), author: z.enum(['user', 'support']), body: z.string().min(1).max(4000), createdAt: z.number().int().nonnegative() }).strict();
export const supportTicketSchema = z.object({ id: z.string().min(1), reference: z.string().min(1), category: z.string().min(1).max(64), subject: z.string().min(1).max(160), description: z.string().min(1).max(4000), context: supportContextSchema.nullable(), status: z.enum(['submitted', 'open', 'waiting_user', 'resolved', 'closed']), messages: z.array(supportMessageSchema), createdAt: z.number().int().nonnegative(), updatedAt: z.number().int().nonnegative(), rating: z.number().int().min(1).max(5).nullable(), version: z.number().int().positive() }).superRefine((value, ctx) => { if (value.rating !== null && !['resolved', 'closed'].includes(value.status)) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'rating requires resolution' }); });
export type SupportTicket = z.infer<typeof supportTicketSchema>;
export const supportOperationSchema = z.object({ id: z.string().min(1), operationId: z.string().min(1), kind: z.enum(['submit_ticket', 'reply', 'feedback', 'report_transaction', 'report_assistant', 'rate']), draftId: z.string().nullable(), ticketId: z.string().nullable(), status: z.enum(['pending', 'submitted', 'failed', 'cancelled']), safeFailure: safeFailureSchema.nullable(), requestedAt: z.number().int().nonnegative(), completedAt: z.number().int().nonnegative().nullable() }).superRefine((value, ctx) => { if (value.status === 'submitted' && value.completedAt === null) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'submitted needs completion' }); if (value.status === 'failed' && value.safeFailure === null) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'failed needs category' }); });
export type SupportOperation = z.infer<typeof supportOperationSchema>; export type SupportReplyInput = Pick<SupportDraft, 'description'>;
export const supportArticleSchema = z.object({ id: z.string().min(1), kind: z.enum(['faq', 'help', 'whats_new']), titleKey: z.string().min(1), bodyKey: z.string().min(1), searchTerms: z.array(z.string()), category: z.string().min(1), version: z.string().min(1), publishedAt: z.number().int().nonnegative() }).strict();
export type SupportArticle = z.infer<typeof supportArticleSchema>;
export function canRateTicket(status: SupportTicket['status']) { return status === 'resolved' || status === 'closed'; }
export function canTransitionTicket(from: SupportTicket['status'], to: SupportTicket['status']) { return (from === 'submitted' && to === 'open') || (from === 'open' && ['waiting_user', 'resolved', 'closed'].includes(to)) || (from === 'waiting_user' && ['open', 'resolved', 'closed'].includes(to)) || (from === 'resolved' && to === 'closed'); }
export function replaySupportOperation(operations: readonly SupportOperation[], operationId: string) { return operations.find((operation) => operation.operationId === operationId) ?? null; }
