export type EngagementMethod = 'GET' | 'POST' | 'PUT';

export interface EngagementRoute {
  method: EngagementMethod;
  path: string;
  operation: string;
  status: 200 | 201 | 202;
  idempotent: boolean;
}

export interface EngagementAdminRoute extends EngagementRoute {
  permission: string;
  recentAuth: boolean;
}

export const ENGAGEMENT_CUSTOMER_ROUTES: readonly EngagementRoute[] = Object.freeze([
  {
    method: 'GET',
    path: 'notifications',
    operation: 'listNotifications',
    status: 200,
    idempotent: false,
  },
  {
    method: 'GET',
    path: 'notifications/preferences',
    operation: 'getNotificationPreferences',
    status: 200,
    idempotent: false,
  },
  {
    method: 'PUT',
    path: 'notifications/preferences',
    operation: 'replaceNotificationPreferences',
    status: 200,
    idempotent: true,
  },
  {
    method: 'GET',
    path: 'notifications/:notificationId',
    operation: 'getNotification',
    status: 200,
    idempotent: false,
  },
  {
    method: 'POST',
    path: 'notifications/:notificationId/read',
    operation: 'setNotificationRead',
    status: 200,
    idempotent: true,
  },
  {
    method: 'POST',
    path: 'notifications/:notificationId/actions',
    operation: 'actOnNotification',
    status: 200,
    idempotent: true,
  },
  {
    method: 'GET',
    path: 'support/categories',
    operation: 'listSupportCategories',
    status: 200,
    idempotent: false,
  },
  {
    method: 'GET',
    path: 'support/tickets',
    operation: 'listSupportTickets',
    status: 200,
    idempotent: false,
  },
  {
    method: 'POST',
    path: 'support/tickets',
    operation: 'createSupportTicket',
    status: 201,
    idempotent: true,
  },
  {
    method: 'GET',
    path: 'support/tickets/:ticketId',
    operation: 'getSupportTicket',
    status: 200,
    idempotent: false,
  },
  {
    method: 'POST',
    path: 'support/tickets/:ticketId/messages',
    operation: 'addSupportMessage',
    status: 201,
    idempotent: true,
  },
  {
    method: 'POST',
    path: 'support/tickets/:ticketId/close',
    operation: 'closeSupportTicket',
    status: 200,
    idempotent: true,
  },
  {
    method: 'POST',
    path: 'support/tickets/:ticketId/reopen',
    operation: 'reopenSupportTicket',
    status: 200,
    idempotent: true,
  },
  {
    method: 'POST',
    path: 'support/tickets/:ticketId/attachments/uploads',
    operation: 'initializeSupportAttachment',
    status: 201,
    idempotent: true,
  },
  {
    method: 'POST',
    path: 'support/tickets/:ticketId/attachments/finalize',
    operation: 'finalizeSupportAttachment',
    status: 202,
    idempotent: true,
  },
  {
    method: 'GET',
    path: 'support/attachments/:attachmentId/download',
    operation: 'downloadSupportAttachment',
    status: 200,
    idempotent: false,
  },
  { method: 'GET', path: 'feedback', operation: 'listFeedback', status: 200, idempotent: false },
  { method: 'POST', path: 'feedback', operation: 'createFeedback', status: 201, idempotent: true },
  {
    method: 'GET',
    path: 'feedback/:feedbackId',
    operation: 'getFeedback',
    status: 200,
    idempotent: false,
  },
  {
    method: 'GET',
    path: 'abuse-reports',
    operation: 'listOwnAbuseReports',
    status: 200,
    idempotent: false,
  },
  {
    method: 'POST',
    path: 'abuse-reports',
    operation: 'createAbuseReport',
    status: 202,
    idempotent: true,
  },
  {
    method: 'GET',
    path: 'content',
    operation: 'listPublishedContent',
    status: 200,
    idempotent: false,
  },
  {
    method: 'GET',
    path: 'content/:contentKey',
    operation: 'getPublishedContent',
    status: 200,
    idempotent: false,
  },
]);

export const ENGAGEMENT_ADMIN_ROUTES: readonly EngagementAdminRoute[] = Object.freeze([
  {
    method: 'GET',
    path: 'admin/communications/templates',
    operation: 'adminListNotificationTemplates',
    status: 200,
    idempotent: false,
    permission: 'communications.templates.manage',
    recentAuth: false,
  },
  {
    method: 'POST',
    path: 'admin/communications/templates',
    operation: 'adminCreateNotificationTemplate',
    status: 201,
    idempotent: true,
    permission: 'communications.templates.manage',
    recentAuth: true,
  },
  {
    method: 'POST',
    path: 'admin/communications/templates/:templateId/actions',
    operation: 'adminActOnNotificationTemplate',
    status: 200,
    idempotent: true,
    permission: 'communications.templates.manage',
    recentAuth: true,
  },
  {
    method: 'POST',
    path: 'admin/notifications/audience-preview',
    operation: 'adminPreviewNotificationAudience',
    status: 200,
    idempotent: true,
    permission: 'notifications.audience.preview',
    recentAuth: true,
  },
  {
    method: 'GET',
    path: 'admin/notifications/campaigns',
    operation: 'adminListNotificationCampaigns',
    status: 200,
    idempotent: false,
    permission: 'notifications.campaigns.read',
    recentAuth: false,
  },
  {
    method: 'POST',
    path: 'admin/notifications/campaigns',
    operation: 'adminCreateNotificationCampaign',
    status: 201,
    idempotent: true,
    permission: 'notifications.campaigns.manage',
    recentAuth: true,
  },
  {
    method: 'GET',
    path: 'admin/notifications/campaigns/:campaignId',
    operation: 'adminGetNotificationCampaign',
    status: 200,
    idempotent: false,
    permission: 'notifications.campaigns.detail.read',
    recentAuth: false,
  },
  {
    method: 'POST',
    path: 'admin/notifications/campaigns/:campaignId/actions',
    operation: 'adminActOnNotificationCampaign',
    status: 200,
    idempotent: true,
    permission: 'notifications.campaigns.manage',
    recentAuth: true,
  },
  {
    method: 'GET',
    path: 'admin/notifications/deliveries',
    operation: 'adminListNotificationDeliveries',
    status: 200,
    idempotent: false,
    permission: 'notifications.delivery.read',
    recentAuth: false,
  },
  {
    method: 'POST',
    path: 'admin/notifications/deliveries/:deliveryId/retry',
    operation: 'adminRetryNotificationDelivery',
    status: 202,
    idempotent: true,
    permission: 'notifications.campaigns.manage',
    recentAuth: true,
  },
  {
    method: 'GET',
    path: 'admin/support/tickets',
    operation: 'adminListSupportTickets',
    status: 200,
    idempotent: false,
    permission: 'support.tickets.read',
    recentAuth: false,
  },
  {
    method: 'GET',
    path: 'admin/support/tickets/:ticketId',
    operation: 'adminGetSupportTicket',
    status: 200,
    idempotent: false,
    permission: 'support.tickets.detail.read',
    recentAuth: false,
  },
  {
    method: 'POST',
    path: 'admin/support/tickets/:ticketId/actions',
    operation: 'adminActOnSupportTicket',
    status: 200,
    idempotent: true,
    permission: 'support.tickets.manage',
    recentAuth: true,
  },
  {
    method: 'POST',
    path: 'admin/support/tickets/:ticketId/notes',
    operation: 'adminAddSupportInternalNote',
    status: 201,
    idempotent: true,
    permission: 'support.tickets.notes',
    recentAuth: true,
  },
  {
    method: 'GET',
    path: 'admin/support/categories',
    operation: 'adminListSupportCategories',
    status: 200,
    idempotent: false,
    permission: 'support.categories.read',
    recentAuth: false,
  },
  {
    method: 'POST',
    path: 'admin/support/categories',
    operation: 'adminCreateSupportCategory',
    status: 201,
    idempotent: true,
    permission: 'support.categories.manage',
    recentAuth: true,
  },
  {
    method: 'POST',
    path: 'admin/support/categories/:categoryId/actions',
    operation: 'adminActOnSupportCategory',
    status: 200,
    idempotent: true,
    permission: 'support.categories.manage',
    recentAuth: true,
  },
  {
    method: 'GET',
    path: 'admin/feedback',
    operation: 'adminListFeedback',
    status: 200,
    idempotent: false,
    permission: 'feedback.read',
    recentAuth: false,
  },
  {
    method: 'GET',
    path: 'admin/feedback/:feedbackId',
    operation: 'adminGetFeedback',
    status: 200,
    idempotent: false,
    permission: 'feedback.read',
    recentAuth: false,
  },
  {
    method: 'POST',
    path: 'admin/feedback/:feedbackId/actions',
    operation: 'adminActOnFeedback',
    status: 200,
    idempotent: true,
    permission: 'feedback.manage',
    recentAuth: true,
  },
  {
    method: 'GET',
    path: 'admin/abuse-reports',
    operation: 'adminListAbuseReports',
    status: 200,
    idempotent: false,
    permission: 'feedback.abuse.manage',
    recentAuth: false,
  },
  {
    method: 'POST',
    path: 'admin/abuse-reports/:reportId/actions',
    operation: 'adminActOnAbuseReport',
    status: 200,
    idempotent: true,
    permission: 'feedback.abuse.manage',
    recentAuth: true,
  },
  {
    method: 'GET',
    path: 'admin/content',
    operation: 'adminListContent',
    status: 200,
    idempotent: false,
    permission: 'content.manage',
    recentAuth: false,
  },
  {
    method: 'GET',
    path: 'admin/content/:contentId',
    operation: 'adminGetContent',
    status: 200,
    idempotent: false,
    permission: 'content.manage',
    recentAuth: false,
  },
  {
    method: 'POST',
    path: 'admin/content',
    operation: 'adminCreateContent',
    status: 201,
    idempotent: true,
    permission: 'content.manage',
    recentAuth: true,
  },
  {
    method: 'POST',
    path: 'admin/content/:contentId/actions',
    operation: 'adminActOnContent',
    status: 200,
    idempotent: true,
    permission: 'content.manage',
    recentAuth: true,
  },
]);
