import type { PoolService } from '../../src/platform/database/pool.service';
import { createLivePool, describeLiveDatabase } from '../live-database';

describeLiveDatabase('migration application', () => {
  let pool: PoolService;

  beforeAll(() => {
    pool = createLivePool();
  });
  afterAll(async () => pool.onModuleDestroy());

  it('is idempotent and creates only the registered application inventory', async () => {
    const liveTestFlag = process.env.MASARIFI_LIVE_DATABASE_TESTS;
    const processKind = process.env.MASARIFI_PROCESS_KIND;
    const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
    delete process.env.MASARIFI_LIVE_DATABASE_TESTS;
    process.env.MASARIFI_PROCESS_KIND = 'migration';
    delete process.env.SUPABASE_SERVICE_ROLE_KEY;
    try {
      const { runMigrations } = await import('../../src/migration');
      await expect(runMigrations()).resolves.toBe(0);
      await expect(runMigrations()).resolves.toBe(0);
    } finally {
      process.env.MASARIFI_LIVE_DATABASE_TESTS = liveTestFlag;
      process.env.MASARIFI_PROCESS_KIND = processKind;
      process.env.SUPABASE_SERVICE_ROLE_KEY = serviceRoleKey;
    }

    const schemas = await pool.query<{ name: string }>(
      "select nspname as name from pg_namespace where nspname in ('private', 'audit') order by name",
    );
    expect(schemas.rows.map((row) => row.name)).toEqual(['audit', 'private']);

    const tables = await pool.query<{ name: string }>(
      "select schemaname || '.' || tablename as name from pg_tables where schemaname in ('private', 'audit') order by name",
    );
    expect(tables.rows.map((row) => row.name)).toEqual([
      'audit.audit_events',
      'audit.transaction_revisions',
      'private.account_deletion_requests',
      'private.ai_failure_events',
      'private.ai_feature_routes',
      'private.ai_models',
      'private.ai_prompt_test_cases',
      'private.ai_prompt_versions',
      'private.ai_providers',
      'private.ai_safety_rules',
      'private.ai_usage_events',
      'private.clerk_webhook_events',
      'private.feature_flag_rules',
      'private.feature_flags',
      'private.idempotency_keys',
      'private.import_attempts',
      'private.job_attempts',
      'private.job_runs',
      'private.maintenance_windows',
      'private.notification_deliveries',
      'private.outbox_events',
      'private.planning_job_claims',
      'private.planning_reminder_intents',
      'private.privacy_export_requests',
      'private.provider_health_checks',
      'private.raw_ingestion_payloads',
      'private.report_output_attempts',
      'private.retention_holds',
      'private.retention_policies',
      'private.scheduled_jobs',
      'private.security_incident_timeline',
      'private.security_incidents',
      'private.support_access_grants',
      'private.support_access_requests',
      'private.support_attachments',
      'private.support_internal_notes',
      'private.sync_cursor_positions',
      'private.system_incidents',
      'private.system_settings',
      'private.user_job_quota_events',
    ]);

    const functions = await pool.query<{ name: string }>(
      `select proname as name
       from pg_proc join pg_namespace on pg_namespace.oid = pg_proc.pronamespace
       where nspname = 'private'
       order by name`,
    );
    expect(functions.rows.map((row) => row.name)).toEqual([
      'accept_admin_invitation',
      'accept_import_item',
      'ack_client_sync_cursor',
      'add_support_message',
      'admin_active_session_count',
      'admin_has_permission',
      'advance_report_schedule',
      'ai_assert_owner',
      'ai_history_turn_limit',
      'ai_owner_data_counts',
      'ai_route_is_compliant',
      'ai_workload_available',
      'allocate_obligation_payment',
      'apply_parser_result',
      'assert_active_profile',
      'assert_active_sync_device',
      'assert_admin_permission',
      'assert_automatic_tracking_account',
      'assert_engagement_admin',
      'assert_support_grant',
      'attach_account_tracking_sync_snapshot',
      'attach_credit_card_terms_sync_snapshot',
      'attach_outbox_sync_metadata',
      'attach_planning_sync_metadata',
      'cancel_assistant_message',
      'capture_report_delivery_webhook',
      'capture_report_snapshot',
      'check_sync_reconciliation',
      'claim_ai_work',
      'claim_client_mutations',
      'claim_due_jobs',
      'claim_duplicate_decision',
      'claim_idempotency_key',
      'claim_import_session',
      'claim_notification_deliveries',
      'claim_outbox_batch',
      'claim_parser_corpus',
      'claim_planning_job',
      'claim_planning_match_candidates',
      'claim_planning_obligation_schedules',
      'claim_planning_overdue',
      'claim_planning_reminders',
      'claim_planning_salary_cycles',
      'claim_review_decision',
      'claim_sync_idempotency_key',
      'claim_tracking_admin_idempotency',
      'claim_voice_media_purge',
      'clear_credit_card_terms_on_type_change',
      'clear_tracking_history',
      'compact_tracking_history',
      'complete_ai_action',
      'complete_ai_work',
      'complete_client_mutation',
      'complete_idempotency_key',
      'complete_import_attempt',
      'complete_job_attempt',
      'complete_parser_corpus',
      'complete_planning_claim',
      'complete_raw_ingestion_purge',
      'complete_sync_idempotency_key',
      'complete_tracking_admin_idempotency',
      'complete_voice_media_purge',
      'compute_duplicate_candidates',
      'confirm_ai_action',
      'confirm_ai_action',
      'create_abuse_report',
      'create_ai_response_report',
      'create_assistant_conversation',
      'create_feedback',
      'create_import_session',
      'create_notification_event',
      'create_report_schedule',
      'create_review_item',
      'create_support_ticket',
      'create_transaction_conflict',
      'create_voice_session',
      'decide_duplicate_candidate',
      'decide_payment_match',
      'decide_review_item',
      'defer_import_item',
      'delete_ai_owner_data',
      'delete_engagement_owner_data',
      'delete_keyword_rule',
      'delete_report_schedule',
      'delete_sender_rule',
      'delete_tracking_data',
      'delete_voice_category_preference',
      'dispatch_security_alerts',
      'enqueue_assistant_message',
      'enqueue_assistant_message_v2',
      'enqueue_assistant_message_v3',
      'enqueue_credit_card_due_reminders',
      'enqueue_credit_card_due_reminders',
      'enqueue_outbox_event',
      'evaluate_feature_flag',
      'execute_engagement_command',
      'execute_operations_command',
      'execute_operations_job',
      'execute_planning_claim',
      'expire_ai_proposals',
      'export_ai_batch',
      'export_ai_batch',
      'export_engagement_batch',
      'export_tracking_batch',
      'export_tracking_data',
      'finalize_import_session',
      'finalize_voice_session',
      'generate_obligation_schedule',
      'generate_salary_receipts',
      'get_admin_self_context',
      'get_ai_work_input',
      'get_assistant_availability',
      'get_assistant_consent',
      'get_assistant_message_result',
      'get_assistant_work_input_v2',
      'get_category_usage',
      'get_effective_ai_route',
      'get_sync_bounds',
      'get_sync_delta',
      'get_tracking_preferences',
      'get_voice_proposal',
      'get_voice_session',
      'guard_account_balance',
      'guard_account_update',
      'guard_ai_failure_event_change',
      'guard_category_graph',
      'guard_client_mutation',
      'guard_idempotency_key',
      'guard_immutable_engagement_row',
      'guard_job_attempt_update',
      'guard_maintenance_overlap',
      'guard_notification_template',
      'guard_outbox_payload',
      'guard_published_parser_version',
      'guard_report_output_attempt',
      'guard_report_schedule',
      'guard_tracking_history_change',
      'guard_tracking_import_posting',
      'guard_transaction_conflict',
      'guard_transaction_update',
      'heartbeat_job_attempt',
      'invalidate_linked_obligation_payments',
      'invalidate_linked_obligation_payments_after_ledger_status',
      'is_valid_support_scope',
      'jsonb_object_key_count',
      'ledger_account_ids',
      'ledger_actor_is_admin',
      'ledger_apply_posting',
      'ledger_begin',
      'ledger_next_version',
      'ledger_record_revision',
      'ledger_result',
      'ledger_safe_text',
      'ledger_snapshot',
      'ledger_touch_balance',
      'link_salary_receipt',
      'list_assistant_conversations',
      'list_assistant_messages',
      'list_due_report_schedules',
      'list_financial_insights',
      'list_reminder_candidates',
      'list_report_outputs',
      'list_report_work',
      'list_voice_category_preferences',
      'lookup_idempotency_key',
      'mark_notification',
      'mark_planning_overdue',
      'mutate_admin_ai',
      'mutate_tracking_admin',
      'next_sync_cursor',
      'planning_thresholds_valid',
      'post_opening_transaction',
      'post_transaction',
      'prepare_import_session',
      'prevent_retention_hold_overlap',
      'propose_payment_matches',
      'protect_clerk_webhook_receipt',
      'protect_last_super_admin',
      'protect_security_definition',
      'protect_system_role_permissions',
      'publish_ai_prompt_version',
      'publish_ai_prompt_version',
      'publish_parser_version',
      'purge_raw_ingestion_payloads',
      'queue_parser_corpus',
      'queue_raw_ingestion_cleanup',
      'raw_ingestion_payload_registered',
      'read_admin_ai',
      'read_admin_ai',
      'read_admin_overview_activity',
      'read_admin_planning_summary',
      'read_admin_report_counts',
      'read_ai_voice_refs',
      'read_ai_voice_refs',
      'read_due_report_schedule',
      'read_engagement_attachment_refs',
      'read_operations',
      'read_parser_corpus',
      'read_parser_preview',
      'read_report_output',
      'read_report_work',
      'read_safe_platform_meta',
      'read_support_workspace',
      'read_supported_financial_report',
      'read_tracking_admin',
      'read_tracking_raw_refs',
      'reassign_category_transactions',
      'receive_client_mutation',
      'recompute_obligation_schedule_item',
      'reconcile_account_balance',
      'reconcile_ai_state',
      'reconcile_import_session_counts',
      'reconcile_import_sessions',
      'reconcile_planning',
      'record_ai_failure',
      'record_ai_failure',
      'record_ai_generation_hash',
      'record_ai_usage',
      'record_assistant_feedback',
      'record_savings_movement',
      'record_sync_cursor_issued',
      'record_tracking_feedback',
      'record_unsupported_import',
      'refresh_financial_insights',
      'refund_transaction',
      'register_job',
      'register_raw_ingestion_payload',
      'reject_ai_action',
      'reject_ai_immutable_change',
      'reject_ai_prompt_version_change',
      'reject_exchange_rate_change',
      'reject_immutable_change',
      'reject_ledger_evidence_change',
      'reject_planning_history_change',
      'reminder_delivery_eligible',
      'replace_budget_categories',
      'request_job_action',
      'reserve_ai_quota',
      'reserve_ai_quota',
      'reserve_user_job_quota',
      'resolve_category',
      'resolve_exchange_rate',
      'resolve_transaction_conflict',
      'restore_default_keyword_rules',
      'restore_linked_obligation_payments',
      'restore_linked_obligation_payments_after_ledger_status',
      'restore_transaction',
      'retry_client_mutation',
      'retry_report_delivery',
      'reverse_savings_movement',
      'reverse_transaction',
      'revise_transaction',
      'rollup_ai_usage',
      'run_sync_maintenance',
      'save_assistant_result',
      'save_budget',
      'save_deterministic_assistant_message',
      'save_obligation',
      'save_salary_profile',
      'save_savings_goal',
      'save_voice_result',
      'seed_notification_preferences',
      'set_assistant_consent',
      'set_updated_at_and_version',
      'soft_delete_transaction',
      'test_ai_prompt_version',
      'tracking_operational_metrics',
      'tracking_request_id',
      'transfer_funds',
      'transition_report_output',
      'update_assistant_conversation',
      'update_report_schedule',
      'update_tracking_preferences',
      'upsert_keyword_rule',
      'upsert_sender_rule',
      'upsert_voice_category_preference',
      'valid_feature_audience',
      'valid_safe_summary',
      'validate_ai_feature_route',
      'validate_ai_proposal',
      'validate_ai_safety_rule',
      'validate_assistant_action',
      'validate_support_grant_invariant',
    ]);

    const roles = await pool.query<{ name: string; login: boolean }>(
      "select rolname as name, rolcanlogin as login from pg_roles where rolname like 'masarifi_%' order by name",
    );
    expect(roles.rows).toEqual([
      { name: 'masarifi_api', login: false },
      { name: 'masarifi_migration', login: false },
      { name: 'masarifi_worker', login: false },
    ]);

    const buckets = await pool.query<{ id: string; public: boolean }>(
      "select id, public from storage.buckets where id in ('support-attachments', 'report-exports', 'tracking-imports', 'voice-temp') order by id",
    );
    expect(buckets.rows).toEqual([
      { id: 'report-exports', public: false },
      { id: 'support-attachments', public: false },
      { id: 'tracking-imports', public: false },
      { id: 'voice-temp', public: false },
    ]);

    const queue = await pool.query<{ present: boolean }>(
      `select to_regclass('pgmq."q_platform-events"') is not null as present`,
    );
    expect(queue.rows[0]?.present).toBe(true);
  }, 600_000);
});
