export const importsCopy = {
  ar: {
    page: {
      eyebrow: "العمليات / الاستيراد",
      title: "الاستيراد والأتمتة",
      description: "مراقبة التقاط المعاملات آلياً ومراجعة الحالات التي تحتاج تدخلاً.",
      reviewFailures: "مراجعة الفشل",
    },
    analytics: {
      title: "تحليلات الاستيراد حسب المنصة",
      description: "القيم المجمعة موثوقة من العقد ولا تجمع العملاء بين iOS وAndroid.",
      platform: "منصة التحليلات",
      all: "الكل",
      uniqueCustomers: "العملاء الفريدون",
      sessions: "الجلسات",
      failedSessions: "الجلسات الفاشلة",
      topFailedSource: "أعلى مصدر فشلاً",
    },
    metrics: {
      totalImports: "إجمالي عمليات الاستيراد",
      successful: "ناجحة",
      failed: "فاشلة",
      partial: "جزئية",
      pendingReview: "بانتظار المراجعة",
      duplicateCandidates: "مرشحة للتكرار",
      unsupportedFormats: "تنسيقات غير مدعومة",
      averageProcessingTime: "متوسط المعالجة",
    },
    charts: {
      volumeTitle: "حجم الاستيراد حسب المصدر",
      volumeSubtitle: "ناجح مقابل فاشل · بالآلاف",
      volumeSummary: "رسائل Android هي المصدر الأعلى حجماً، بينما الصور تسجل أكبر حجم فشل نسبي.",
      trendTitle: "اتجاه الفشل",
      trendSubtitle: "النسبة المئوية خلال آخر 6 أيام",
      trendSummary: "ارتفع معدل الفشل من 1.4 إلى 2.8 بالمئة.",
      successRateTitle: "معدل النجاح حسب المصدر",
      successRateSubtitle: "آخر 30 يوماً",
      processingTimeTitle: "متوسط وقت المعالجة",
      processingTimeSubtitle: "حسب المصدر",
    },
    sources: {
      "SMS": "SMS",
      "notifications": "الإشعارات",
      "Shortcut": "Shortcut",
      "images": "الصور",
      "CSV": "CSV",
      "PDF": "PDF",
      "Android SMS": "Android SMS",
      "iOS Shortcut": "iOS Shortcut",
      "receipts": "صور الإيصالات",
    },
    failedImports: {
      title: "عمليات الاستيراد الفاشلة",
      description: "بيانات منزوعة المحتوى الحساس ومخصصة للعرض.",
      searchPlaceholder: "معرّف العملية أو المستخدم",
      searchAria: "بحث عمليات الاستيراد",
      allSources: "كل المصادر",
      clearFilter: "مسح",
      columns: {
        id: "المعرّف",
        user: "المستخدم",
        source: "المصدر",
        bank: "البنك",
        failureReason: "سبب الفشل",
        parser: "المحلل",
        attempts: "المحاولات",
        severity: "الخطورة",
        time: "الوقت",
        action: "الإجراء",
      },
      retry: "إعادة المحاولة",
      details: "التفاصيل",
      failureLabel: "الفشل",
      parserLabel: "المحلل",
    },
    dates: {
      "jul20": "20 يوليو",
      "jul21": "21 يوليو",
      "jul22": "22 يوليو",
      "jul23": "23 يوليو",
      "jul24": "24 يوليو",
      "jul25": "25 يوليو",
    }
  },
  en: {
    page: {
      eyebrow: "Operations / Imports",
      title: "Imports and Automation",
      description: "Monitor automated transaction capture and review cases that require intervention.",
      reviewFailures: "Review failures",
    },
    analytics: {
      title: "Import Analytics by Platform",
      description: "All values are aggregated and trusted across iOS and Android.",
      platform: "Analytics Platform",
      all: "All",
      uniqueCustomers: "Unique customers",
      sessions: "Sessions",
      failedSessions: "Failed sessions",
      topFailedSource: "Top failed source",
    },
    metrics: {
      totalImports: "Total import operations",
      successful: "Successful",
      failed: "Failed",
      partial: "Partial",
      pendingReview: "Pending review",
      duplicateCandidates: "Duplicate candidates",
      unsupportedFormats: "Unsupported formats",
      averageProcessingTime: "Average processing time",
    },
    charts: {
      volumeTitle: "Import Volume by Source",
      volumeSubtitle: "Success vs Failure · in thousands",
      volumeSummary: "Android SMS is the highest volume source, while images have the largest relative failure volume.",
      trendTitle: "Failure Trend",
      trendSubtitle: "Percentage over last 6 days",
      trendSummary: "Failure rate increased from 1.4% to 2.8%.",
      successRateTitle: "Success Rate by Source",
      successRateSubtitle: "Last 30 days",
      processingTimeTitle: "Average Processing Time",
      processingTimeSubtitle: "By source",
    },
    sources: {
      "SMS": "SMS",
      "notifications": "Notifications",
      "Shortcut": "Shortcut",
      "images": "Images",
      "CSV": "CSV",
      "PDF": "PDF",
      "Android SMS": "Android SMS",
      "iOS Shortcut": "iOS Shortcut",
      "receipts": "Receipt images",
    },
    failedImports: {
      title: "Failed Imports",
      description: "Masked data for display purposes.",
      searchPlaceholder: "Process or user ID",
      searchAria: "Search imports",
      allSources: "All sources",
      clearFilter: "Clear",
      columns: {
        id: "ID",
        user: "User",
        source: "Source",
        bank: "Bank",
        failureReason: "Failure Reason",
        parser: "Parser",
        attempts: "Attempts",
        severity: "Severity",
        time: "Time",
        action: "Action",
      },
      retry: "Retry",
      details: "Details",
      failureLabel: "Failure",
      parserLabel: "Parser",
    },
    dates: {
      "jul20": "Jul 20",
      "jul21": "Jul 21",
      "jul22": "Jul 22",
      "jul23": "Jul 23",
      "jul24": "Jul 24",
      "jul25": "Jul 25",
    }
  }
} as const;
